// Mocks generated by Mockito 5.0.15 from annotations
// in movies_list/test/features/home/data/datasources/movies_remote_data_source_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:movies_list/features/home/data/datasources/client_http_services_data_sources.dart'
    as _i3;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeClient_0 extends _i1.Fake implements _i2.Client {}

/// A class which mocks [HttpServiceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpServiceImpl extends _i1.Mock implements _i3.HttpServiceImpl {
  MockHttpServiceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Client get client => (super.noSuchMethod(Invocation.getter(#client),
      returnValue: _FakeClient_0()) as _i2.Client);
  @override
  _i4.Future<dynamic> get(String? path, {dynamic data}) =>
      (super.noSuchMethod(Invocation.method(#get, [path], {#data: data}),
          returnValue: Future<dynamic>.value()) as _i4.Future<dynamic>);
  @override
  String toString() => super.toString();
}
