name: movies_list
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.13.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Service locator
  get_it: ^7.2.0
  # Bloc for state management
  flutter_bloc: ^7.3.3
  bloc_test: ^8.5.0
  # Value equality
  equatable: ^2.0.3
  # Functional programming thingies
  dartz: ^0.10.0
  # Remote API
  internet_connection_checker: ^0.0.1+3
  http: ^0.13.3
  # Mock class for tests
  mockito: ^5.0.15
  shared_preferences: ^2.0.7
  # Layout
  cached_network_image: ^3.1.0
  flutter_typeahead: ^3.2.1
  google_fonts: ^2.1.0
  flutter_rating_bar: ^4.0.0
  skeleton_text: ^3.0.0
  
  url_launcher: ^6.0.10






  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.2
  

flutter:
  
  uses-material-design: true

  assets:
    - assets/icons/

